### ISSUE TITLE
Mobile browser Language was set up English as primary language

### ISSUE THREAD

**Issue by TonyBan99** [TonyBan99/JA-mobile-browser-version#3]
![mobile browser language](https://user-images.githubusercontent.com/40814023/42262815-9a259e06-7f96-11e8-96fb-014b562409cf.jpeg)

Please set up Language as Vietnamese language ( but will consider first)

**Comment by ThibaultDetraz** [comment]
Should we make sure that the VN version is 100% translated before switching?
